config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  get 'about/index'
  # get 'home/index'
  root 'friends#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @about_me = "Hi, my name is Kender ROMAIN"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  # Verify if the user is not authenticated let him access to these methods : index & show
  before_action :authenticate_user!, except: %i[ index show ] 
  before_action :correct_user, only: %i[ edit update destroy ]


  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # Verify if the user iis linked to the friend
  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path , notice: "You are not authorized" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter,:user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.erb
<h1>About</h1>
<p><%=@about_me%></p>

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.text_field :first_name,class:"form-control",placeholder:"First name" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :last_name,class:"form-control",placeholder:"Last name" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :email,class:"form-control",placeholder:"example@gmail.com" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :phone,class:"form-control",placeholder:"Phone Number" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :twitter,class:"form-control",placeholder:"@JohnDoe" %>
  </div>

  <div class="mb-3">
    <%= form.hidden_field :user_id,class:"form-control",placeholder:"User ID" ,value:current_user.id %>
  </div>

  <div>
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend,class:"btn btn-secondary" %> 
  <%= link_to "Back to friends", friends_path,class:"btn btn-dark" %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>
<table class="table table-bordered table-striped table-hover">
  <thead class="table-dark">
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Twitter</th>
    <th>User</th>
    <th></th>
  </thead>
  <tbody>
     <% @friends.each do |friend| %>
       <% if current_user  == friend.user %>
        <tr>
          <td><%= link_to "#{friend.first_name} #{friend.last_name}", friend %></td>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
          <td><%= friend.user_id %></td>
          <td><%= link_to "Delete this friend",friend,data:{turbo_method: :delete, turbo_confirm:'Are you sure' },class:"btn btn-danger btn-sm" %></td>
          
       </tr>
       <% end %>
    <% end %>
   
  </tbody>
</table>
<%= link_to "New friend", new_friend_path,class:"btn btn-secondary" %>

<% else %>
  <h1>Welcome</h1>
  <p>Welcome to Friends App!</p>
<% end %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>
<br>
<div>
  <%= link_to "Back to friends", friends_path,class:"btn btn-dark" %>
</div>

app/views/friends/show.html.erb
<div class="jmt-4 p-5 bg-secondary text-white rounded">
  <h1 class="display-4"><%=@friend.first_name%> <%=@friend.last_name%></h1>
  <p class="lead"><%=@friend.email%> | <%=@friend.phone%> | <%=@friend.twitter%></p>
  <hr class="my-4">
  <%= link_to "Edit this friend", edit_friend_path(@friend),class:"btn btn-dark" %> 
  <%= link_to "Delete this friend", @friend,data:{turbo_method: :delete, turbo_confirm:'Are you sure' }, class:"btn btn-danger inline" %> 
  <%= link_to "Back to friends", friends_path,class:"btn btn-dark" %>

</div>

app/views/home/index.html.erb
<h1>Welcome</h1>
<p>Welcome to Friends App!</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <title>Friends App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'partials/header'%>
    <div class="container">
      <br>
      <% if notice %>
        <%= render 'partials/alert'%>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  </body>
</html>

app/views/partials/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%=notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <!-- This code means : Create a link and when we  click on 'Friends App' redirect to the root page -->
    <%= link_to 'Friends App', root_path, class:"navbar-brand"%>
    <!-- <a class="navbar-brand" href="#">Friends App</a> -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      
            <li class="nav-item">
              <%= link_to 'About',about_index_path,class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'Friends',friends_path,class:"nav-link"%>
            </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Add Friend',new_friend_path,class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= button_to 'Sign Out',destroy_user_session_path,method: :delete%>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile',edit_user_registration_path,class:"nav-link"%>
          </li>
          <% else %>
            
            <li class="nav-item">
              <%= link_to 'Sign Up',new_user_registration_path,class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign In',new_user_session_path,class:"nav-link"%>
            </li>
          <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>